version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      retries: 5

  airflow:
    image: apache/airflow:2.7.1-python3.11
    restart: always
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__LOGGING__LOGGING_LEVEL: "INFO"
    volumes:
      - ./:/opt/airflow/project   # Весь проект в контейнер
      - ./dags:/opt/airflow/dags  # DAG-и отдельно
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/requirements.txt
    ports:
      - "8080:8080"
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y xvfb &&
      pip install --no-cache-dir -r /requirements.txt &&
      airflow db init &&
      airflow webserver
      "
